openapi: 3.0.3
info:
  title: NS WhatsApp Service
  description: WhatsApp Service API
  version: 1.0.3
tags:
  - name: WhatsApp Service - Send
    description: API to send a whatsapp message
  - name: WhatsApp Service - Webhook
    description: Webhook for processing MO requests.
  - name: NS MO Processing API
    description: MO processing 

paths:
  /v1/send:
    post:
      tags:
        - WhatsApp Service - Send
      summary: Send a WhatsApp message
      operationId: createWhatsAppMessageRequest
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/Authorization'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WhatsAppServiceSendRequest'
            examples:
              default:
                $ref: "#/components/examples/WhatsAppServiceSendRequest"
      responses:
        '201':
          $ref: '#/components/responses/successful_201'
        '400':
          $ref: '#/components/responses/invalidRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        '500':
          $ref: '#/components/responses/internalServerError'
  /v1/mowhatsapp:
    post:
      tags:
        - WhatsApp Service - Webhook
      summary: Callback from syniverse for MO requests
      operationId: createWhatsAppMORequest
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/Authorization'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WhatsAppServiceMORequest'
            examples:
              default:
                $ref: "#/components/examples/WhatsAppServiceMORequest"
      responses:
        '201':
          $ref: '#/components/responses/successful_mo_201'
        '400':
          $ref: '#/components/responses/invalidRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        '500':
          $ref: '#/components/responses/internalServerError'
  /mbl/v2/mowhatsapp:
    post:
      tags:
        - NS MO Processing API
      summary: API to process the MO request received from Whatsapp service
      operationId: createMOProcessingRequest
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/Authorization'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WhatsAppMOMessageRequestInfo'
            examples:
              default:
                $ref: "#/components/examples/WhatsAppMOMessageRequestInfo"
      responses:
        '201':
          $ref: '#/components/responses/successful_mo_201'
        '400':
          $ref: '#/components/responses/invalidRequest'
        '401':
          $ref: '#/components/responses/unauthorized'
        '500':
          $ref: '#/components/responses/internalServerError'
          
components:
  schemas:
    WhatsAppServiceSendRequest:
      type: object
      properties:
        senderId:
          type: string
          description: "WhatsApp senderID - from number"
          example: "+1890890890"
        address:
          type: string
          description: "WhatsApp to number - end user whatsapp number"
          example: "+1840359390"
        message:
          type: string
          description: "Whatsapp message content"
          example: "Hello, this is a test message"
        telephoneCountryCode:
          type: string
          description: "Country code"
          example: "1"
        fiID:
          type: string
          description: "FIID"
          example: "00516"
        aggregator:
          type: string
          description: "Third party vendor. ex: syniverse"
          example: "syniverse"
        sourceSystem:
          type: string
          description: "Source application whether MFA or MBL"
          example: "MFA"
      required:
        - senderId
        - address
        - message
        - telephoneCountryCode
        - fiId
        - aggregator
        - sourceSystem
    WhatsAppServiceSendResponse:
      type: object
      properties:
        id:
          type: string
          description: "Response received from syniverse"
          example: "bx634Akt6aEDUOTsClQQc6WK27"
    WhatsAppServiceMORequest:
      type: object
      properties:
        topic:
          type: string
          description: "Syniverse topic"
          example: "SCG-Message"
        attempt:
          type: string
          description: "Message attempt"
          example: "1"
        event:
          $ref: '#/components/schemas/EventInfo'
        event-id:
          type: string
          description: "event id"
          example: "jX5nAV9USriK2LkS6e0D0g"
      required:
        - topic
        - attempt
        - event
        - event-id
    EventInfo:
      type: object
      properties:
        fld-val-list:
          $ref: '#/components/schemas/FldValList'
        evt-tp:
          type: string
          description: "event type"
          example: "mo_message_received"
        timestamp:
          type: string
          description: "timestamp"
          example: "2017-11-30T17:17:46.615Z"
      required:
        - fld-val-list
        - evt-tp
        - timestamp
    FldValList:
      type: object
      properties:
        sender_id_alias:
          type: string
          description: "sender id"
          example: "ERp2WG5dG2Gfl9WzcohqP5"
        sender_id_id:
          type: string
          description: "sender id"
          example: "ERp2WG5dG2Gfl9WzcohqP5"
        message_body:
          type: string
          description: "message content"
          example: "HELP"
        message_id:
          type: string
          description: "message id"
          example: "vy3E72K3Tr7lHxUXe1S776"
        to_address:
          type: string
          description: "to address"
          example: "+1890890890"
        from_address:
          type: string
          description: "from address"
          example: "+1840359390"
    WhatsAppServiceMOResponse:
      type: object
      properties:
        status:
          type: string
          description: "mo status"
          example: "Success"
        senderId:
          type: string
          description: "sender id"
          example: "ERp2WG5dG2Gfl9WzcohqP5"
        message_id:
          type: string
          description: "message id"
          example: "vy3E72K3Tr7lHxUXe1S776"
    WhatsAppMOMessageRequestInfo:
      type: object
      properties:
        senderId:
          type: string
          description: "sender id"
          example: "ERp2WG5dG2Gfl9WzcohqP5"
        messageId:
          type: string
          description: "message id"
          example: "vy3E72K3Tr7lHxUXe1S776"
        toAddress:
          type: string
          description: "to address"
          example: "+1890890890"
        fromAddress:
          type: string
          description: "from address"
          example: "+1840359390"
        messageBody:
          type: string
          description: "message content"
          example: "HELP"
      required:
        - senderId
        - messageId
        - toAddress
        - fromAddress
        - messageBody
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: "A unique error code for identifying the issue."
          example: "100400"
        message:
          type: string
          description: "A detailed error message explaining the issue."
          example: "Missing mandatory field '{fieldName}'."

  parameters:
    transactionId:
      name: transactionId
      in: header
      required: true
      description: Unique Identifier for the transaction.
      schema:
        type: string
      example: "12345-abcde-67890"
    Authorization:
      name: Authorization
      in: header
      required: true
      description: Authorization token, Global JWT
      schema:
        type: string
      example: "Bearer XXX"

  responses:
    successful_200: #200
      description: The request was successful. Return updated Preference
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WhatsAppServiceSendResponse'
          examples:
            default:
              $ref: "#/components/examples/WhatsAppServiceSendResponse"

    successful_201: #201
      description: The request was successful.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WhatsAppServiceSendResponse'
          examples:
            default:
              $ref: "#/components/examples/WhatsAppServiceSendResponse"
    
    successful_mo_201: #201
      description: The request was successful.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WhatsAppServiceMOResponse'
          examples:
            default:
              $ref: "#/components/examples/WhatsAppServiceMOResponse"

    invalidRequest: #400
      description: Bad Request - Missing Required Fields or Invalid value
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            missingOrInvalidField:
              value:
                code: "100400"
                message: "'{fieldName}' is required, must not be blank."


    unauthorized: #401
      description: Authentication is required. Valid autorization token should pass
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            missingOrInvalidToken:
              value:
                code: "100401"
                message: "Authentication failed or token is missing."

    internalServerError: #500
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            unexpectedError:
              value:
                code: "100500"
                message: "An unexpected error occurred. Please try again later."
  examples:
  
    WhatsAppServiceSendRequest:
      summary: default
      value:
        senderId: "+1890890890"
        address: "+1840359390"
        message: "Hello, this is a test message"
        telephoneCountryCode: "1"
        fiID: "00516"
        aggregator: "syniverse"
        sourceSystem: "MFA"

    WhatsAppServiceSendResponse:
      summary: default
      value:
        id: "bx634Akt6aEDUOTsClQQc6WK27"

    WhatsAppServiceMORequest:
      summary: default
      value: 
        topic: "SCG-Message"
        attempt: 1
        event: 
          fld-val-list: 
            sender_id_alias: "ERp2WG5dG2Gfl9WzcohqP5"
            sender_id_id: "ERp2WG5dG2Gfl9WzcohqP5"
            message_body: "BAL"
            message_id: "vy3E72K3Tr7lHxUXe1S776"
            to_address: "+1890890890"
            from_address: "+1840359390"
          evt-tp: "mo_message_received"
          timestamp: "2020-04-23T20:40:15.613Z"
        event-id: "6OEBYfs3RruOOV2fgdayuQ"
    WhatsAppServiceMOResponse:
      summary: default
      value:
        status: "Success"
        senderId: "ERp2WG5dG2Gfl9WzcohqP5"
        messageId: "vy3E72K3Tr7lHxUXe1S776"
    WhatsAppMOMessageRequestInfo:
      summary: default
      value:
        senderId: "ERp2WG5dG2Gfl9WzcohqP5"
        messageId: "vy3E72K3Tr7lHxUXe1S776"
        toAddress: "+1890890890"
        fromAddress: "+1840359390"
        messageBody: "HELP"
